apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  redis-host: dGV6ZGEtcmVkaXMta3lnOGNoLnNlcnZlcmxlc3MudXNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=
  redis-port: NjM3OQ==
  redis-password: cGFzc3dvcmQ=