apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - name: redis-app
        image: 319945231254.dkr.ecr.us-east-1.amazonaws.com/tezda-ecr:latest
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-port
---
apiVersion: v1
kind: Service
metadata:
  name: redis-app
  namespace: redis
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31000  # You can choose any available port in the range 30000-32767
  selector:
    app: redis-app
